### ISSUE TITLE
how to get sidebar to stay in one place?

### ISSUE THREAD

**Issue by iandouglas** [JugglerX/hugo-whisper-theme#21]
On Chrome 76, when viewing your demo site (https://hugo-whisper.netlify.com/docs/), clicking on the various sidebad entries makes the sidebar shift left/right. What would it take to keep that in one place? is it the content on the various pages that increases/decreases the whole page width which is auto-margined in CSS maybe?

**Comment by JugglerX** [comment]
Hi, I don't see the problem. Could you post some screenshots.

**Comment by iandouglas** [comment]
Start on https://hugo-whisper.netlify.com/docs/install-theme/

Click through the sidebar menu ... "Install Hugo" and "Hugo Whisper" shift all content to the right, and "Install Theme", "Configuration" and "Specimen" shift content to the left. Not much, maybe 5 pixels, but it's noticeable.

Windows 10, Chrome 76.0.3809.100

Open the Inspect tool, click on your `<body>` tag and look at the computed styles. "Install Hugo" and "Hugo Whisper" look like they're setting the width to 1920px where the others are 1903px. The difference in width makes the sidebar move back and forth. Just curious how you could lock that in place.

**Comment by JugglerX** [comment]
I think it's because some pages have a browser scrollbar and others do not. That's just what happens when the browser has a scrollbar.

I suppose if its really annoying you could do some CSS trickery to fix the issue, maybe try `calc` or you maybe using `overflow`. Maybe you can set the sidebar to `position: fixed`. I'm sure there will be a way to "fix" this, but It's not something I would fix, it will just lead to more problems trying to interfere with the default browser behaviour.

**Comment by iandouglas** [comment]
okay, thanks then.
